# -*- coding: utf-8 -*-
"""numpyPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuFvsqPBT8kAN9PhF7OOlhyyXEZ9qh0_
"""

import numpy as np

a=np.array([1,2,3])

print(a)

b=np.array([[1,2],[3,4],[5,6]])
print(b)

b.ndim

b.shape

b=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(b)

"""Array Manipulation

Changing shape
"""

import numpy as np
a=np.arange(9)
print(a)

#reshaping the above array
b=a.reshape(3,3)
print(b)

print(b.flatten())

print(b.transpose())

"""**Numpy Arithmetic Operation**"""

a=np.arange(6).reshape(2,3)
print(a)

b=np.array([[10,10,10],[11,2,13]])
print(b)

np.add(a,b)

np.multiply(a,b)

"""Slicing"""

a=np.arange(10)
print(a)

a[3:5]

"""Iterating array"""

a=np.arange(0,46,5)
a=a.reshape(2,5)
a

for x in np.nditer(a):
  print(x)

for x in np.nditer(a, order='C'):    #C-type iteration(row major)
  print(x)

for x in np.nditer(a, order='F'):   #F type iteration(column major)
  print(x)

"""Joinning Array"""

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("Before joining")
print(a,"\n\n",b)
print("Row wise joining")
print(np.concatenate((a,b),axis=0))
print("Column wise joining")
print(np.concatenate((a,b),axis=1))

"""Splitting Array"""

a=np.arange(9)
print(a)

b=np.split(a,3)
print(b)

np.split(a,[3,8])

"""Resizing array"""

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

np.resize(a,(3,2))